# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{github_cloner}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vasiliy Ermolovich"]
  s.date = %q{2011-03-09}
  s.default_executable = %q{github_cloner}
  s.description = %q{an easy way to clone all your projects from github}
  s.email = %q{younash@gmail.com}
  s.executables = ["github_cloner"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/github_cloner",
    "github_cloner.gemspec",
    "lib/github_cloner.rb",
    "lib/github_cloner/github_helper.rb",
    "lib/github_cloner/version.rb",
    "pkg/github_cloner-0.1.gem",
    "pkg/github_cloner-0.2.gem",
    "pkg/github_cloner-0.3.0.gem",
    "test/helper.rb",
    "test/test_github_cloner.rb"
  ]
  s.homepage = %q{http://github.com/nashby/github_cloner}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{an easy way to clone all your projects from github}
  s.test_files = [
    "test/helper.rb",
    "test/test_github_cloner.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

